{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "6ZScHv201Fhg"
   },
   "source": [
    "# Classification of Structured Data with Keras preprocessing layers\n",
    "\n",
    "**Author:** [Mike Fournigault](https://www.linkedin.com/in/mike-fournigault-57312071/)<br>\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "9stLJR7J1Fhl"
   },
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "\n",
    "# Only the TensorFlow backend supports string inputs.\n",
    "os.environ[\"KERAS_BACKEND\"] = \"tensorflow\"\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import tensorflow as tf\n",
    "import keras\n",
    "from keras import layers\n",
    "\n",
    "sys.path.append(os.path.abspath(\"../../src/\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Adding the instrumentation of the TF code with debugger V2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Enabled dumping callback in thread MainThread (dump root: ./tfdbg2_logdir, tensor debug mode: FULL_HEALTH)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<tensorflow.python.debug.lib.debug_events_writer.DebugEventsWriter at 0x7f17a4018c10>"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "tf.debugging.experimental.enable_dump_debug_info(\n",
    "    dump_root=\"./tfdbg2_logdir\", tensor_debug_mode=\"FULL_HEALTH\", circular_buffer_size=-1\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Loading and preparing the datasets"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Reading and merging catalog and mapping files"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "columns = [\"OBJECT_ID\", \"FITS_ID\", \"CCD_ID\", \"ISO0\", \"BACKGROUND\", \"ELLIPTICITY\", \"ELONGATION\", \"CLASS_STAR\", \"FLAGS\", \"EXPTIME\"]\n",
    "data_path = \"../../data/\"\n",
    "proc_path = os.path.join(data_path, \"processed\")\n",
    "fm_path = os.path.join(data_path, \"for_modeling\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "def custom_reader_func(datasets):\n",
    "  return datasets.interleave(lambda x: x, num_parallel_calls=tf.data.AUTOTUNE)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "current directory:  /mnt/c/Users/mikef/git/astro_iqa/src/modeling\n",
      "Content of the directory:  ['.gitattributes', 'map_images_labels.json', 'map_images_labels_cadc.json', 'map_images_labels_cadc2.json', 'map_images_labels_ngc0869.json', 'map_images_labels_ngc0896.json', 'map_images_labels_ngc7000.json', 'modelling.md', 'objects_catalog_cadc2.parquet.gz', 'objects_catalog_ngc0869.parquet.gz', 'objects_catalog_ngc0896.parquet.gz', 'objects_catalog_ngc7000.parquet.gz', 'test_dataset', 'training_dataset', 'validation_dataset']\n",
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/2592363969.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/2592363969.py\n",
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/4098658339.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/4098658339.py\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-03-21 16:58:42.947773: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n",
      "Your kernel may have been built without NUMA support.\n",
      "2025-03-21 16:58:43.180691: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n",
      "Your kernel may have been built without NUMA support.\n",
      "2025-03-21 16:58:43.180751: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n",
      "Your kernel may have been built without NUMA support.\n",
      "2025-03-21 16:58:43.184608: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n",
      "Your kernel may have been built without NUMA support.\n",
      "2025-03-21 16:58:43.184907: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n",
      "Your kernel may have been built without NUMA support.\n",
      "2025-03-21 16:58:43.185024: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n",
      "Your kernel may have been built without NUMA support.\n",
      "2025-03-21 16:58:43.546602: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n",
      "Your kernel may have been built without NUMA support.\n",
      "2025-03-21 16:58:43.546903: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n",
      "Your kernel may have been built without NUMA support.\n",
      "2025-03-21 16:58:43.547008: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2022] Could not identify NUMA node of platform GPU id 0, defaulting to 0.  Your kernel may not have been built with NUMA support.\n",
      "2025-03-21 16:58:43.547215: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node\n",
      "Your kernel may have been built without NUMA support.\n",
      "2025-03-21 16:58:43.547305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6722 MB memory:  -> device: 0, name: Quadro P4000, pci bus id: 0000:01:00.0, compute capability: 6.1\n"
     ]
    }
   ],
   "source": [
    "# Load the tensorflow Datasets\n",
    "print(\"current directory: \", os.getcwd())\n",
    "print(\"Content of the directory: \", os.listdir(fm_path))\n",
    "training_dataset = tf.data.Dataset.load(path=os.path.join(fm_path, \"training_dataset\"), reader_func=custom_reader_func)\n",
    "validation_dataset = tf.data.Dataset.load(path=os.path.join(fm_path, \"validation_dataset\"), reader_func=custom_reader_func)\n",
    "testing_dataset = tf.data.Dataset.load(path=os.path.join(fm_path, \"test_dataset\"), reader_func=custom_reader_func)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/3560779233.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/3560779233.py\n"
     ]
    }
   ],
   "source": [
    "# As we separated the labels from the features, we need to convert the labels to StringLookups\n",
    "label_lookup = tf.keras.layers.StringLookup()\n",
    "label_lookup.adapt(training_dataset.map(lambda x, y: y))\n",
    "\n",
    "training_dataset = training_dataset.map(lambda x, y: (x, label_lookup(y)))\n",
    "validation_dataset = validation_dataset.map(lambda x, y: (x, label_lookup(y)))\n",
    "testing_dataset = testing_dataset.map(lambda x, y: (x, label_lookup(y)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "from tensorflow.keras.layers import StringLookup, Normalization\n",
    "from tensorflow.keras.utils import Sequence\n",
    "\n",
    "\n",
    "#"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Testing our datasets for sanity checks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/2108282043.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/2108282043.py\n",
      "Every feature: ['ISO0', 'FITS_ID', 'FLAGS', 'ELLIPTICITY', 'CCD_ID', 'CLASS_STAR', 'gt_label1', 'ELONGATION', 'EXPTIME', 'BACKGROUND']\n",
      "A batch of ELLIPTICITY: tf.Tensor(\n",
      "[[0.78264153]\n",
      " [0.47585982]\n",
      " [0.6671052 ]\n",
      " [0.17121279]\n",
      " [0.76049113]\n",
      " [0.7568648 ]\n",
      " [0.34455228]\n",
      " [0.7747539 ]\n",
      " [0.5960636 ]\n",
      " [0.51149046]\n",
      " [0.861753  ]\n",
      " [0.80339986]\n",
      " [0.29815495]\n",
      " [0.9918808 ]\n",
      " [0.9840157 ]\n",
      " [0.50382775]\n",
      " [0.9969438 ]\n",
      " [0.30246472]\n",
      " [0.72142637]\n",
      " [0.78332305]\n",
      " [0.05240852]\n",
      " [0.71980107]\n",
      " [0.6715517 ]\n",
      " [0.3731296 ]\n",
      " [0.7682065 ]\n",
      " [0.64978206]\n",
      " [0.0649904 ]\n",
      " [0.57324195]\n",
      " [0.7616688 ]\n",
      " [0.8111505 ]\n",
      " [0.7778587 ]\n",
      " [0.82150084]\n",
      " [0.84908044]\n",
      " [0.36903435]\n",
      " [0.7625987 ]\n",
      " [0.87358457]\n",
      " [0.50443614]\n",
      " [0.71031165]\n",
      " [0.8691399 ]\n",
      " [0.4297365 ]\n",
      " [0.5382836 ]\n",
      " [0.61038566]\n",
      " [0.57938814]\n",
      " [0.3192072 ]\n",
      " [0.9550641 ]\n",
      " [0.66174954]\n",
      " [0.78321755]\n",
      " [0.8423984 ]\n",
      " [0.63916516]\n",
      " [0.7373588 ]\n",
      " [0.8843243 ]\n",
      " [0.7907473 ]\n",
      " [0.6789378 ]\n",
      " [0.9104991 ]\n",
      " [0.5105925 ]\n",
      " [0.7571713 ]\n",
      " [0.43734515]\n",
      " [0.41002744]\n",
      " [0.7346002 ]\n",
      " [0.16985095]\n",
      " [0.689749  ]\n",
      " [0.19809073]\n",
      " [0.35283744]\n",
      " [0.57368517]\n",
      " [0.3434478 ]\n",
      " [0.829654  ]\n",
      " [0.53604543]\n",
      " [0.77394193]\n",
      " [0.1665442 ]\n",
      " [0.26813328]\n",
      " [0.75022423]\n",
      " [0.83346736]\n",
      " [0.84124076]\n",
      " [0.6040305 ]\n",
      " [0.6765069 ]\n",
      " [0.47183406]\n",
      " [0.68120444]\n",
      " [0.2850539 ]\n",
      " [0.6838376 ]\n",
      " [0.67505246]\n",
      " [0.76479954]\n",
      " [0.8121023 ]\n",
      " [0.2936033 ]\n",
      " [0.6441796 ]\n",
      " [0.39044064]\n",
      " [0.66655755]\n",
      " [0.51878554]\n",
      " [0.38944626]\n",
      " [0.49137437]\n",
      " [0.15274692]\n",
      " [0.11796802]\n",
      " [0.44199586]\n",
      " [0.30318016]\n",
      " [0.7290684 ]\n",
      " [0.60162723]\n",
      " [0.77300763]\n",
      " [0.82453454]\n",
      " [0.7032535 ]\n",
      " [0.42567503]\n",
      " [0.798229  ]\n",
      " [0.68411255]\n",
      " [0.7089109 ]\n",
      " [0.33081394]\n",
      " [0.850976  ]\n",
      " [0.32198715]\n",
      " [0.7829107 ]\n",
      " [0.90701103]\n",
      " [0.7614255 ]\n",
      " [0.70228744]\n",
      " [0.7906921 ]\n",
      " [0.71921706]\n",
      " [0.71657646]\n",
      " [0.80630505]\n",
      " [0.24177891]\n",
      " [0.41272414]\n",
      " [0.70259637]\n",
      " [0.5256473 ]\n",
      " [0.4329391 ]\n",
      " [0.8183003 ]\n",
      " [0.6757046 ]\n",
      " [0.8093251 ]\n",
      " [0.5778816 ]\n",
      " [0.4466738 ]\n",
      " [0.82680076]\n",
      " [0.8823953 ]\n",
      " [0.7673331 ]\n",
      " [0.43880385]\n",
      " [0.8005881 ]], shape=(128, 1), dtype=float32)\n",
      "A batch of targets: tf.Tensor(\n",
      "[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1\n",
      " 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1\n",
      " 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1\n",
      " 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1], shape=(128,), dtype=int64)\n"
     ]
    }
   ],
   "source": [
    "\n",
    "[(train_features, label_batch)] = training_dataset.take(1)\n",
    "print('Every feature:', list(train_features.keys()))\n",
    "print('A batch of ELLIPTICITY:', train_features['ELLIPTICITY'])\n",
    "print('A batch of targets:', label_batch )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/4065386777.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/4065386777.py\n",
      "Every feature: ['ISO0', 'FITS_ID', 'FLAGS', 'ELLIPTICITY', 'CCD_ID', 'CLASS_STAR', 'gt_label1', 'ELONGATION', 'EXPTIME', 'BACKGROUND']\n",
      "A batch of ELLIPTICITY: tf.Tensor(\n",
      "[[0.35624993]\n",
      " [0.26592666]\n",
      " [0.83772945]\n",
      " [0.7027589 ]\n",
      " [0.88597155]\n",
      " [0.7756514 ]\n",
      " [0.21023828]\n",
      " [0.7262485 ]\n",
      " [0.34354144]\n",
      " [0.6349837 ]\n",
      " [0.72408426]\n",
      " [0.59848714]\n",
      " [0.42157894]\n",
      " [0.866242  ]\n",
      " [0.5675301 ]\n",
      " [0.5993735 ]\n",
      " [0.2283591 ]\n",
      " [0.527534  ]\n",
      " [0.3625645 ]\n",
      " [0.31038666]\n",
      " [0.7874818 ]\n",
      " [0.5818038 ]\n",
      " [0.37114233]\n",
      " [0.4620301 ]\n",
      " [0.8003256 ]\n",
      " [0.64659506]\n",
      " [0.6382233 ]\n",
      " [0.47726828]\n",
      " [0.45862538]\n",
      " [0.18544888]\n",
      " [0.76987904]\n",
      " [0.39453256]\n",
      " [0.7794554 ]\n",
      " [0.5655196 ]\n",
      " [0.46227401]\n",
      " [0.645999  ]\n",
      " [0.2810517 ]\n",
      " [0.6341995 ]\n",
      " [0.6006255 ]\n",
      " [0.6220186 ]\n",
      " [0.870293  ]\n",
      " [0.6359205 ]\n",
      " [0.33743584]\n",
      " [0.31926966]\n",
      " [0.3068831 ]\n",
      " [0.6903769 ]\n",
      " [0.6277549 ]\n",
      " [0.88080883]\n",
      " [0.67995584]\n",
      " [0.5032791 ]\n",
      " [0.834937  ]\n",
      " [0.7598072 ]\n",
      " [0.9273336 ]\n",
      " [0.7901139 ]\n",
      " [0.57319057]\n",
      " [0.47191143]\n",
      " [0.07389432]\n",
      " [0.57480085]\n",
      " [0.7690511 ]\n",
      " [0.36880493]\n",
      " [0.19443697]\n",
      " [0.6735662 ]\n",
      " [0.61170447]\n",
      " [0.81006134]\n",
      " [0.618001  ]\n",
      " [0.39990997]\n",
      " [0.34612292]\n",
      " [0.8843246 ]\n",
      " [0.6440246 ]\n",
      " [0.732832  ]\n",
      " [0.69683576]\n",
      " [0.56479657]\n",
      " [0.48739707]\n",
      " [0.48323923]\n",
      " [0.16805959]\n",
      " [0.5470501 ]\n",
      " [0.36865604]\n",
      " [0.65704477]\n",
      " [0.74074495]\n",
      " [0.2882867 ]\n",
      " [0.59703803]\n",
      " [0.42968166]\n",
      " [0.41213024]\n",
      " [0.71477777]\n",
      " [0.31967604]\n",
      " [0.37837857]\n",
      " [0.3695222 ]\n",
      " [0.76142377]\n",
      " [0.6137464 ]\n",
      " [0.7515202 ]\n",
      " [0.32994097]\n",
      " [0.16723853]\n",
      " [0.1378395 ]\n",
      " [0.48594457]\n",
      " [0.09349465]\n",
      " [0.7779721 ]\n",
      " [0.8955715 ]\n",
      " [0.5439607 ]\n",
      " [0.4286638 ]\n",
      " [0.06474519]\n",
      " [0.09777188]\n",
      " [0.4454139 ]\n",
      " [0.42785233]\n",
      " [0.23471278]\n",
      " [0.4445656 ]\n",
      " [0.59160244]\n",
      " [0.59955376]\n",
      " [0.5979763 ]\n",
      " [0.005279  ]\n",
      " [0.13457412]\n",
      " [0.08792222]\n",
      " [0.03428143]\n",
      " [0.07404011]\n",
      " [0.17803103]\n",
      " [0.4072792 ]\n",
      " [0.17508471]\n",
      " [0.54828185]\n",
      " [0.5558824 ]\n",
      " [0.02256876]\n",
      " [0.8028465 ]\n",
      " [0.5923157 ]\n",
      " [0.18170583]\n",
      " [0.28632164]\n",
      " [0.07471132]\n",
      " [0.36728144]\n",
      " [0.0608784 ]\n",
      " [0.1553871 ]\n",
      " [0.1833086 ]], shape=(128, 1), dtype=float32)\n",
      "A batch of targets: tf.Tensor(\n",
      "[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1\n",
      " 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1\n",
      " 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1\n",
      " 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1], shape=(128,), dtype=int64)\n"
     ]
    }
   ],
   "source": [
    "\n",
    "[(validation_features, label_batch)] = validation_dataset.take(1)\n",
    "print('Every feature:', list(validation_features.keys()))\n",
    "print('A batch of ELLIPTICITY:', validation_features['ELLIPTICITY'])\n",
    "print('A batch of targets:', label_batch )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "testing dataset elements:  ({'ISO0': TensorSpec(shape=(None, 1), dtype=tf.float32, name=None), 'FITS_ID': TensorSpec(shape=(None, 1), dtype=tf.string, name=None), 'FLAGS': TensorSpec(shape=(None, 1), dtype=tf.int16, name=None), 'ELLIPTICITY': TensorSpec(shape=(None, 1), dtype=tf.float32, name=None), 'CCD_ID': TensorSpec(shape=(None, 1), dtype=tf.uint8, name=None), 'CLASS_STAR': TensorSpec(shape=(None, 1), dtype=tf.float32, name=None), 'gt_label1': TensorSpec(shape=(None, 1), dtype=tf.string, name=None), 'ELONGATION': TensorSpec(shape=(None, 1), dtype=tf.float32, name=None), 'EXPTIME': TensorSpec(shape=(None, 1), dtype=tf.float32, name=None), 'BACKGROUND': TensorSpec(shape=(None, 1), dtype=tf.float32, name=None)}, TensorSpec(shape=(None,), dtype=tf.int64, name=None))\n",
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/3965214781.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/3965214781.py\n",
      "Every feature: ['ISO0', 'FITS_ID', 'FLAGS', 'ELLIPTICITY', 'CCD_ID', 'CLASS_STAR', 'gt_label1', 'ELONGATION', 'EXPTIME', 'BACKGROUND']\n",
      "A batch of ELLIPTICITY: tf.Tensor(\n",
      "[[0.73774564]\n",
      " [0.76792455]\n",
      " [0.88322127]\n",
      " [0.58652276]\n",
      " [0.16661912]\n",
      " [0.51338685]\n",
      " [0.6752592 ]\n",
      " [0.7821367 ]\n",
      " [0.9199253 ]\n",
      " [0.82767737]\n",
      " [0.71259534]\n",
      " [0.8504267 ]\n",
      " [0.73135257]\n",
      " [0.17061126]\n",
      " [0.37238264]\n",
      " [0.43729168]\n",
      " [0.7280412 ]\n",
      " [0.78416   ]\n",
      " [0.5399429 ]\n",
      " [0.6657138 ]\n",
      " [0.38972604]\n",
      " [0.7642939 ]\n",
      " [0.46526092]\n",
      " [0.23398477]\n",
      " [0.7239486 ]\n",
      " [0.33794022]\n",
      " [0.5051317 ]\n",
      " [0.9145947 ]\n",
      " [0.4661945 ]\n",
      " [0.76679707]\n",
      " [0.68116105]\n",
      " [0.6290997 ]\n",
      " [0.48241347]\n",
      " [0.4203686 ]\n",
      " [0.6685171 ]\n",
      " [0.6181395 ]\n",
      " [0.4611932 ]\n",
      " [0.4934095 ]\n",
      " [0.61133075]\n",
      " [0.15771002]\n",
      " [0.8090322 ]\n",
      " [0.5679193 ]\n",
      " [0.6499221 ]\n",
      " [0.381589  ]\n",
      " [0.43768197]\n",
      " [0.8798876 ]\n",
      " [0.87038845]\n",
      " [0.1964882 ]\n",
      " [0.5628014 ]\n",
      " [0.41616786]\n",
      " [0.38565606]\n",
      " [0.5602262 ]\n",
      " [0.3846472 ]\n",
      " [0.33895576]\n",
      " [0.3895166 ]\n",
      " [0.7603219 ]\n",
      " [0.67568207]\n",
      " [0.7295542 ]\n",
      " [0.7046386 ]\n",
      " [0.832752  ]\n",
      " [0.41808504]\n",
      " [0.6205281 ]\n",
      " [0.41730136]\n",
      " [0.3103459 ]\n",
      " [0.53169274]\n",
      " [0.3770436 ]\n",
      " [0.545013  ]\n",
      " [0.5386816 ]\n",
      " [0.7154781 ]\n",
      " [0.7511518 ]\n",
      " [0.3981058 ]\n",
      " [0.6258426 ]\n",
      " [0.35214978]\n",
      " [0.35847527]\n",
      " [0.21373963]\n",
      " [0.6705345 ]\n",
      " [0.53383327]\n",
      " [0.8948314 ]\n",
      " [0.64663744]\n",
      " [0.46111202]\n",
      " [0.4263937 ]\n",
      " [0.37339664]\n",
      " [0.4922856 ]\n",
      " [0.18169528]\n",
      " [0.66675854]\n",
      " [0.03657931]\n",
      " [0.61486685]\n",
      " [0.31771737]\n",
      " [0.02606612]\n",
      " [0.41770923]\n",
      " [0.05697733]\n",
      " [0.22539347]\n",
      " [0.17264754]\n",
      " [0.1214512 ]\n",
      " [0.16534293]\n",
      " [0.74831074]\n",
      " [0.08036727]\n",
      " [0.10256493]\n",
      " [0.0639596 ]\n",
      " [0.31593692]\n",
      " [0.76827407]\n",
      " [0.0402835 ]\n",
      " [0.23683023]\n",
      " [0.7440008 ]\n",
      " [0.40748733]\n",
      " [0.18772507]\n",
      " [0.04180872]\n",
      " [0.24583393]\n",
      " [0.6031759 ]\n",
      " [0.0738585 ]\n",
      " [0.12724751]\n",
      " [0.29674762]\n",
      " [0.05415499]\n",
      " [0.07722813]\n",
      " [0.05361938]\n",
      " [0.07025009]\n",
      " [0.18771768]\n",
      " [0.12731653]\n",
      " [0.03913939]\n",
      " [0.4557594 ]\n",
      " [0.4996367 ]\n",
      " [0.05014533]\n",
      " [0.13377064]\n",
      " [0.05213982]\n",
      " [0.13982576]\n",
      " [0.4859289 ]\n",
      " [0.1102826 ]\n",
      " [0.0579018 ]], shape=(128, 1), dtype=float32)\n",
      "A batch of targets: tf.Tensor(\n",
      "[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1\n",
      " 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1\n",
      " 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1\n",
      " 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1], shape=(128,), dtype=int64)\n"
     ]
    }
   ],
   "source": [
    "print(\"testing dataset elements: \", testing_dataset.element_spec)\n",
    "[(test_features, label_batch)] = testing_dataset.take(1)\n",
    "print('Every feature:', list(test_features.keys()))\n",
    "print('A batch of ELLIPTICITY:', test_features['ELLIPTICITY'])\n",
    "# print(\"a batch of features: \", test_features)\n",
    "print('A batch of targets:', label_batch )\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/2625977780.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/2625977780.py\n"
     ]
    }
   ],
   "source": [
    "# Fonction pour séparer les features et les labels\n",
    "# def prepare_data(features, labels):\n",
    "#     gt_label1 = labels['gt_label1']  # Récupérer la colonne cible\n",
    "#     return features, gt_label1\n",
    "# training_dataset = training_dataset.map(prepare_data)\n",
    "# validation_dataset = validation_dataset.map(prepare_data)\n",
    "# testing_dataset = testing_dataset.map(prepare_data)\n",
    "# Prefetch the data\n",
    "training_dataset = training_dataset.prefetch(buffer_size=tf.data.AUTOTUNE)\n",
    "validation_dataset = validation_dataset.prefetch(buffer_size=tf.data.AUTOTUNE)\n",
    "testing_dataset = testing_dataset.prefetch(buffer_size=tf.data.AUTOTUNE)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "# from data_acquisition_understanding.dnn_datasets_preparation import read_and_concat_catalogs\n",
    "# test_df = read_and_concat_catalogs([os.path.join(fm_path, \"objects_catalog_ngc0869.parquet.gz\")])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "FEATURE_NAMES = [\n",
    "    # \"OBJECT_ID\", # object\n",
    "    \"FITS_ID\", # object\n",
    "    \"CCD_ID\", # uint8\n",
    "    \"ISO0\", # float32\n",
    "    \"BACKGROUND\", # float32\n",
    "    \"ELLIPTICITY\", # float32\n",
    "    \"ELONGATION\", # float32\n",
    "    \"CLASS_STAR\", # float32\n",
    "    \"FLAGS\", # int16\n",
    "    \"EXPTIME\", # float32\n",
    "    \"gt_label1\" # object\n",
    "]\n",
    "\n",
    "NUMERIC_FEATURE_NAMES = {\n",
    "    \"ISO0\": \"float32\",\n",
    "    \"BACKGROUND\": \"float32\",\n",
    "    \"ELLIPTICITY\": \"float32\",\n",
    "    \"ELONGATION\": \"float32\",\n",
    "    \"CLASS_STAR\": \"float32\",\n",
    "    \"EXPTIME\": \"float32\"\n",
    "}\n",
    "\n",
    "CATEGORICAL_FEATURE_NAMES = {\n",
    "    \"FITS_ID\": \"string\",\n",
    "    \"CCD_ID\": \"uint8\",\n",
    "    \"FLAGS\": \"int16\",\n",
    "    # \"gt_label1\": \"string\" # is already part of the label\n",
    "}\n",
    "\n",
    "ID_COLUMNS = {\n",
    "    \"OBJECT_ID\": \"string\"\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "65k_ZOAv1Fhw"
   },
   "source": [
    "## Create model inputs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_normalization_layer(name, dataset):\n",
    "    print(\"Processing numerical feature: \", name)\n",
    "    # Create a Normalization layer for the feature.\n",
    "    normalizer = layers.Normalization(axis=None)\n",
    "\n",
    "    # Prepare a Dataset that only yields the feature.\n",
    "    feature_ds = dataset.map(lambda x, y: x[name])\n",
    "\n",
    "    # Learn the statistics of the data.\n",
    "    normalizer.adapt(feature_ds)\n",
    "\n",
    "    return normalizer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_category_encoding_layer(name, dataset, dtype, max_tokens=None):\n",
    "    # Create a layer that turns strings into integer indices.\n",
    "    print(\"Processing categorical feature: \", name)\n",
    "    if dtype == 'string':\n",
    "        print(\" ... StringLookup\")\n",
    "        index = layers.StringLookup(max_tokens=max_tokens)\n",
    "    # Otherwise, create a layer that turns integer values into integer indices.\n",
    "    else:\n",
    "        print(\" ... IntegerLookup\")\n",
    "        index = layers.IntegerLookup(max_tokens=max_tokens)\n",
    "\n",
    "    # Prepare a `tf.data.Dataset` that only yields the feature.\n",
    "    feature_ds = dataset.map(lambda x, y: x[name])\n",
    "\n",
    "    # Learn the set of possible values and assign them a fixed integer index.\n",
    "    index.adapt(feature_ds)\n",
    "\n",
    "    # Encode the integer indices.\n",
    "    encoder = layers.CategoryEncoding(num_tokens=index.vocabulary_size())\n",
    "\n",
    "    # Apply multi-hot encoding to the indices. The lambda function captures the\n",
    "    # layer, so you can use them, or include them in the Keras Functional model later.\n",
    "    return lambda feature: encoder(index(feature))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Encode input features\n",
    "\n",
    "For categorical features, we encode them using `layers.Embedding` using the\n",
    "`encoding_size` as the embedding dimensions. For the numerical features,\n",
    "we apply linear transformation using `layers.Dense` to project each feature into\n",
    "`encoding_size`-dimensional vector. Thus, all the encoded features will have the\n",
    "same dimensionality."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "def encode_inputs(dataset, numeric_headers, categorical_headers):\n",
    "\n",
    "    all_inputs = {}\n",
    "    encoded_features = []\n",
    "\n",
    "    # Numerical features.\n",
    "    for feat_name, dtype in numeric_headers.items():\n",
    "        numeric_col = tf.keras.Input(shape=(1,), name=feat_name)\n",
    "        normalization_layer = get_normalization_layer(feat_name, dataset)\n",
    "        encoded_numeric_col = normalization_layer(numeric_col)\n",
    "        all_inputs[feat_name] = numeric_col\n",
    "        encoded_features.append(encoded_numeric_col)\n",
    "\n",
    "\n",
    "    for feat_name, dtype in categorical_headers.items():\n",
    "        categorical_col = tf.keras.Input(shape=(1,), name=feat_name, dtype=dtype)\n",
    "        encoding_layer = get_category_encoding_layer(name=feat_name,\n",
    "                                                    dataset=dataset,\n",
    "                                                    dtype=dtype,\n",
    "                                                    max_tokens=10)\n",
    "        encoded_categorical_col = encoding_layer(categorical_col)\n",
    "        all_inputs[feat_name] = categorical_col\n",
    "        encoded_features.append(encoded_categorical_col)\n",
    "    \n",
    "\n",
    "    return all_inputs, encoded_features"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing numerical feature:  ISO0\n",
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/1145242043.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/1145242043.py\n",
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/2670252640.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/2670252640.py\n",
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/2499078454.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/2499078454.py\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-03-21 16:59:29.509260: I external/local_tsl/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing numerical feature:  BACKGROUND\n",
      "Processing numerical feature:  ELLIPTICITY\n",
      "Processing numerical feature:  ELONGATION\n",
      "Processing numerical feature:  CLASS_STAR\n",
      "Processing numerical feature:  EXPTIME\n",
      "Processing categorical feature:  FITS_ID\n",
      " ... StringLookup\n",
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/1190837587.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/1190837587.py\n",
      "Processing categorical feature:  CCD_ID\n",
      " ... IntegerLookup\n",
      "Processing categorical feature:  FLAGS\n",
      " ... IntegerLookup\n",
      "encoded features dypes:  [tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32]\n"
     ]
    }
   ],
   "source": [
    "# testing the function\n",
    "all_inputs, encoded_features = encode_inputs(validation_dataset, NUMERIC_FEATURE_NAMES, CATEGORICAL_FEATURE_NAMES)\n",
    "\n",
    "print(\"encoded features dypes: \", [x.dtype for x in encoded_features])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/3970338192.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/3970338192.py\n",
      "Processing numerical feature:  ELLIPTICITY\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<tf.Tensor: shape=(128, 1), dtype=float32, numpy=\n",
       "array([[ 1.2284503 ],\n",
       "       [ 1.3497897 ],\n",
       "       [ 1.8133597 ],\n",
       "       [ 0.6204332 ],\n",
       "       [-1.0678602 ],\n",
       "       [ 0.32637793],\n",
       "       [ 0.97721297],\n",
       "       [ 1.406932  ],\n",
       "       [ 1.9609343 ],\n",
       "       [ 1.590036  ],\n",
       "       [ 1.1273293 ],\n",
       "       [ 1.6815034 ],\n",
       "       [ 1.2027459 ],\n",
       "       [-1.0518092 ],\n",
       "       [-0.2405533 ],\n",
       "       [ 0.02042446],\n",
       "       [ 1.1894319 ],\n",
       "       [ 1.4150672 ],\n",
       "       [ 0.4331511 ],\n",
       "       [ 0.93883413],\n",
       "       [-0.17082123],\n",
       "       [ 1.3351921 ],\n",
       "       [ 0.13287951],\n",
       "       [-0.79700536],\n",
       "       [ 1.172977  ],\n",
       "       [-0.37903488],\n",
       "       [ 0.29318678],\n",
       "       [ 1.9395019 ],\n",
       "       [ 0.13663316],\n",
       "       [ 1.3452564 ],\n",
       "       [ 1.0009425 ],\n",
       "       [ 0.7916211 ],\n",
       "       [ 0.20184423],\n",
       "       [-0.0476176 ],\n",
       "       [ 0.95010537],\n",
       "       [ 0.7475537 ],\n",
       "       [ 0.11652456],\n",
       "       [ 0.24605568],\n",
       "       [ 0.7201779 ],\n",
       "       [-1.1036808 ],\n",
       "       [ 1.51507   ],\n",
       "       [ 0.5456349 ],\n",
       "       [ 0.8753409 ],\n",
       "       [-0.2035376 ],\n",
       "       [ 0.02199369],\n",
       "       [ 1.7999561 ],\n",
       "       [ 1.7617632 ],\n",
       "       [-0.9477666 ],\n",
       "       [ 0.52505755],\n",
       "       [-0.06450745],\n",
       "       [-0.18718529],\n",
       "       [ 0.51470345],\n",
       "       [-0.1912416 ],\n",
       "       [-0.37495172],\n",
       "       [-0.17166336],\n",
       "       [ 1.3192221 ],\n",
       "       [ 0.97891325],\n",
       "       [ 1.1955152 ],\n",
       "       [ 1.0953379 ],\n",
       "       [ 1.6104394 ],\n",
       "       [-0.0567991 ],\n",
       "       [ 0.75715744],\n",
       "       [-0.05995002],\n",
       "       [-0.48998255],\n",
       "       [ 0.39997986],\n",
       "       [-0.22181311],\n",
       "       [ 0.45353624],\n",
       "       [ 0.42807984],\n",
       "       [ 1.1389201 ],\n",
       "       [ 1.2823521 ],\n",
       "       [-0.137129  ],\n",
       "       [ 0.7785252 ],\n",
       "       [-0.32190293],\n",
       "       [-0.29647025],\n",
       "       [-0.8784043 ],\n",
       "       [ 0.95821655],\n",
       "       [ 0.4085862 ],\n",
       "       [ 1.8600403 ],\n",
       "       [ 0.86213446],\n",
       "       [ 0.11619816],\n",
       "       [-0.02339277],\n",
       "       [-0.23647638],\n",
       "       [ 0.24153683],\n",
       "       [-1.007244  ],\n",
       "       [ 0.9430347 ],\n",
       "       [-1.5907073 ],\n",
       "       [ 0.73439544],\n",
       "       [-0.46034425],\n",
       "       [-1.6329774 ],\n",
       "       [-0.05831009],\n",
       "       [-1.5086936 ],\n",
       "       [-0.8315481 ],\n",
       "       [-1.043622  ],\n",
       "       [-1.2494656 ],\n",
       "       [-1.0729915 ],\n",
       "       [ 1.2709291 ],\n",
       "       [-1.4146504 ],\n",
       "       [-1.325401  ],\n",
       "       [-1.4806203 ],\n",
       "       [-0.46750286],\n",
       "       [ 1.3511951 ],\n",
       "       [-1.575814  ],\n",
       "       [-0.78556466],\n",
       "       [ 1.2536002 ],\n",
       "       [-0.09940896],\n",
       "       [-0.9830003 ],\n",
       "       [-1.5696815 ],\n",
       "       [-0.7493638 ],\n",
       "       [ 0.6873899 ],\n",
       "       [-1.44082   ],\n",
       "       [-1.2261605 ],\n",
       "       [-0.54465663],\n",
       "       [-1.5200413 ],\n",
       "       [-1.4272718 ],\n",
       "       [-1.5221949 ],\n",
       "       [-1.4553282 ],\n",
       "       [-0.98302996],\n",
       "       [-1.225883  ],\n",
       "       [-1.580414  ],\n",
       "       [ 0.09467706],\n",
       "       [ 0.27109316],\n",
       "       [-1.5361629 ],\n",
       "       [-1.1999332 ],\n",
       "       [-1.5281436 ],\n",
       "       [-1.1755875 ],\n",
       "       [ 0.21597858],\n",
       "       [-1.2943708 ],\n",
       "       [-1.5049766 ]], dtype=float32)>"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "[(test_features, label_batch)] = testing_dataset.take(1)\n",
    "test_ellip = test_features['ELLIPTICITY']\n",
    "test_encod_ellip = get_normalization_layer(\"ELLIPTICITY\", testing_dataset)\n",
    "test_encod_ellip(test_ellip)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing categorical feature:  FITS_ID\n",
      " ... StringLookup\n",
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/4012226928.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/4012226928.py\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<tf.Tensor: shape=(128, 10), dtype=float32, numpy=\n",
       "array([[1., 0., 0., ..., 0., 0., 0.],\n",
       "       [1., 0., 0., ..., 0., 0., 0.],\n",
       "       [1., 0., 0., ..., 0., 0., 0.],\n",
       "       ...,\n",
       "       [1., 0., 0., ..., 0., 0., 0.],\n",
       "       [1., 0., 0., ..., 0., 0., 0.],\n",
       "       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)>"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "test_gt_label = test_features['FITS_ID']\n",
    "test_encod_gt_label = get_category_encoding_layer(\"FITS_ID\", testing_dataset, \"string\", 10)\n",
    "test_encod_gt_label(test_gt_label)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "3L7O1kwx1Fhz"
   },
   "source": [
    "## Create Gated Residual and Variable Selection Networks model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {
    "id": "Vc-edCvU1Fhz"
   },
   "outputs": [],
   "source": [
    "def create_model(dataset, numeric_headers, categorical_headers,  \n",
    "                 encoding_size=32, dropout_rate=0.15):\n",
    "    \"\"\"\n",
    "    Create a model with embedding layers for categorical features.\n",
    "    \"\"\"\n",
    "    all_inputs, encoded_inputs = encode_inputs(dataset, numeric_headers, categorical_headers)\n",
    "\n",
    "    all_features = layers.concatenate(encoded_inputs)\n",
    "    x = layers.Dense(32, activation=\"relu\")(all_features)\n",
    "    x = layers.BatchNormalization()(x)\n",
    "    x = layers.Dropout(dropout_rate)(x)\n",
    "\n",
    "    outputs = layers.Dense(units=5, activation=\"sigmoid\")(x)\n",
    "    model = keras.Model(inputs=all_inputs, outputs=outputs)\n",
    "\n",
    "    return model\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "7jcCqDkx1Fhz"
   },
   "source": [
    "## Compile, train, and evaluate the model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {
    "id": "Ul_Y9bz71Fh0"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing numerical feature:  ISO0\n",
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/3533645249.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/3533645249.py\n",
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/3028659529.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/3028659529.py\n",
      "Processing numerical feature:  BACKGROUND\n",
      "Processing numerical feature:  ELLIPTICITY\n",
      "Processing numerical feature:  ELONGATION\n",
      "Processing numerical feature:  CLASS_STAR\n",
      "Processing numerical feature:  EXPTIME\n",
      "Processing categorical feature:  FITS_ID\n",
      " ... StringLookup\n",
      "Processing categorical feature:  CCD_ID\n",
      " ... IntegerLookup\n",
      "Processing categorical feature:  FLAGS\n",
      " ... IntegerLookup\n"
     ]
    }
   ],
   "source": [
    "learning_rate = 0.001\n",
    "dropout_rate = 0.15\n",
    "batch_size = 265\n",
    "num_epochs = 20\n",
    "encoding_size = 16\n",
    "\n",
    "model = create_model(training_dataset, NUMERIC_FEATURE_NAMES, CATEGORICAL_FEATURE_NAMES, \n",
    "                 encoding_size, dropout_rate)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/3752300834.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/3752300834.py\n"
     ]
    }
   ],
   "source": [
    "model.compile(\n",
    "    optimizer=keras.optimizers.Adam(learning_rate=learning_rate),\n",
    "    loss=\"sparse_categorical_crossentropy\",\n",
    "    metrics=[\"accuracy\"]\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Start training the model...\n",
      "WARNING:tensorflow:Failed to read source code from path: /tmp/ipykernel_78405/2435027649.py. Reason: Source path neither exists nor can be loaded as a .par file: /tmp/ipykernel_78405/2435027649.py\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/functional.py:642: UserWarning: Input dict contained keys ['gt_label1'] which did not match any model input. They will be ignored by the model.\n",
      "  inputs = self._flatten_to_reference_inputs(inputs)\n",
      "2025-03-21 17:22:44.459362: I external/local_xla/xla/service/service.cc:168] XLA service 0x7f1665316a10 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n",
      "2025-03-21 17:22:44.459496: I external/local_xla/xla/service/service.cc:176]   StreamExecutor device (0): Quadro P4000, Compute Capability 6.1\n",
      "2025-03-21 17:22:44.465800: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at xla_ops.cc:574 : INVALID_ARGUMENT: Detected unsupported operations when trying to compile graph __inference__update_step_xla_279200[] on XLA_GPU_JIT: DebugNumericSummaryV2 (No registered 'DebugNumericSummaryV2' OpKernel for XLA_GPU_JIT devices compatible with node {{node DebugNumericSummaryV2}}){{node DebugNumericSummaryV2}}\n",
      "The op is created at: \n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
      "File \"tmp/ipykernel_78405/2435027649.py\", line 8, in <module>\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1807, in fit\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1401, in train_function\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1384, in step_function\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1373, in run_step\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1154, in train_step\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 544, in minimize\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1223, in apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 652, in apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1253, in _internal_apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1345, in _distributed_apply_gradients_fn\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1340, in apply_grad_to_update_var\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tensorflow/core/function/polymorphism/function_type.py\", line 356, in placeholder_arguments\n",
      "\ttf2xla conversion failed while converting __inference__update_step_xla_279200[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.\n",
      "2025-03-21 17:22:44.470274: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at xla_ops.cc:574 : INVALID_ARGUMENT: Detected unsupported operations when trying to compile graph __inference__update_step_xla_279307[] on XLA_GPU_JIT: DebugNumericSummaryV2 (No registered 'DebugNumericSummaryV2' OpKernel for XLA_GPU_JIT devices compatible with node {{node DebugNumericSummaryV2}}){{node DebugNumericSummaryV2}}\n",
      "The op is created at: \n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
      "File \"tmp/ipykernel_78405/2435027649.py\", line 8, in <module>\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1807, in fit\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1401, in train_function\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1384, in step_function\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1373, in run_step\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1154, in train_step\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 544, in minimize\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1223, in apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 652, in apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1253, in _internal_apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1345, in _distributed_apply_gradients_fn\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1340, in apply_grad_to_update_var\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tensorflow/core/function/polymorphism/function_type.py\", line 356, in placeholder_arguments\n",
      "\ttf2xla conversion failed while converting __inference__update_step_xla_279307[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.\n",
      "2025-03-21 17:22:44.475706: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at xla_ops.cc:574 : INVALID_ARGUMENT: Detected unsupported operations when trying to compile graph __inference__update_step_xla_279093[] on XLA_GPU_JIT: DebugNumericSummaryV2 (No registered 'DebugNumericSummaryV2' OpKernel for XLA_GPU_JIT devices compatible with node {{node DebugNumericSummaryV2}}){{node DebugNumericSummaryV2}}\n",
      "The op is created at: \n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
      "File \"tmp/ipykernel_78405/2435027649.py\", line 8, in <module>\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1807, in fit\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1401, in train_function\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1384, in step_function\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1373, in run_step\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1154, in train_step\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 544, in minimize\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1223, in apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 652, in apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1253, in _internal_apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1345, in _distributed_apply_gradients_fn\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1340, in apply_grad_to_update_var\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tensorflow/core/function/polymorphism/function_type.py\", line 356, in placeholder_arguments\n",
      "\ttf2xla conversion failed while converting __inference__update_step_xla_279093[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.\n",
      "2025-03-21 17:22:44.494848: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at xla_ops.cc:574 : INVALID_ARGUMENT: Detected unsupported operations when trying to compile graph __inference__update_step_xla_278986[] on XLA_GPU_JIT: DebugNumericSummaryV2 (No registered 'DebugNumericSummaryV2' OpKernel for XLA_GPU_JIT devices compatible with node {{node DebugNumericSummaryV2}}){{node DebugNumericSummaryV2}}\n",
      "The op is created at: \n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
      "File \"tmp/ipykernel_78405/2435027649.py\", line 8, in <module>\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1807, in fit\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1401, in train_function\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1384, in step_function\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1373, in run_step\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1154, in train_step\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 544, in minimize\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1223, in apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 652, in apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1253, in _internal_apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1345, in _distributed_apply_gradients_fn\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1340, in apply_grad_to_update_var\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tensorflow/core/function/polymorphism/function_type.py\", line 356, in placeholder_arguments\n",
      "\ttf2xla conversion failed while converting __inference__update_step_xla_278986[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.\n",
      "2025-03-21 17:22:44.517583: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at xla_ops.cc:574 : INVALID_ARGUMENT: Detected unsupported operations when trying to compile graph __inference__update_step_xla_278770[] on XLA_GPU_JIT: DebugNumericSummaryV2 (No registered 'DebugNumericSummaryV2' OpKernel for XLA_GPU_JIT devices compatible with node {{node DebugNumericSummaryV2}}){{node DebugNumericSummaryV2}}\n",
      "The op is created at: \n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
      "File \"tmp/ipykernel_78405/2435027649.py\", line 8, in <module>\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1807, in fit\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1401, in train_function\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1384, in step_function\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1373, in run_step\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1154, in train_step\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 544, in minimize\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1223, in apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 652, in apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1253, in _internal_apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1345, in _distributed_apply_gradients_fn\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1340, in apply_grad_to_update_var\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tensorflow/core/function/polymorphism/function_type.py\", line 356, in placeholder_arguments\n",
      "\ttf2xla conversion failed while converting __inference__update_step_xla_278770[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.\n",
      "2025-03-21 17:22:44.520529: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at xla_ops.cc:574 : INVALID_ARGUMENT: Detected unsupported operations when trying to compile graph __inference__update_step_xla_278879[] on XLA_GPU_JIT: DebugNumericSummaryV2 (No registered 'DebugNumericSummaryV2' OpKernel for XLA_GPU_JIT devices compatible with node {{node DebugNumericSummaryV2}}){{node DebugNumericSummaryV2}}\n",
      "The op is created at: \n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
      "File \"tmp/ipykernel_78405/2435027649.py\", line 8, in <module>\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1807, in fit\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1401, in train_function\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1384, in step_function\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1373, in run_step\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1154, in train_step\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 544, in minimize\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1223, in apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 652, in apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1253, in _internal_apply_gradients\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1345, in _distributed_apply_gradients_fn\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1340, in apply_grad_to_update_var\n",
      "File \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tensorflow/core/function/polymorphism/function_type.py\", line 356, in placeholder_arguments\n",
      "\ttf2xla conversion failed while converting __inference__update_step_xla_278879[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.\n"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node DebugNumericSummaryV2 defined at (most recent call last):\n<stack traces unavailable>\nDetected at node DebugNumericSummaryV2 defined at (most recent call last):\n<stack traces unavailable>\nDetected unsupported operations when trying to compile graph __inference__update_step_xla_279200[] on XLA_GPU_JIT: DebugNumericSummaryV2 (No registered 'DebugNumericSummaryV2' OpKernel for XLA_GPU_JIT devices compatible with node {{node DebugNumericSummaryV2}}){{node DebugNumericSummaryV2}}\nThe op is created at: \nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 87, in _run_code\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/events.py\", line 80, in _run\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\nFile \"tmp/ipykernel_78405/2435027649.py\", line 8, in <module>\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1807, in fit\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1401, in train_function\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1384, in step_function\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1373, in run_step\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1154, in train_step\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 544, in minimize\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1223, in apply_gradients\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 652, in apply_gradients\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1253, in _internal_apply_gradients\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1345, in _distributed_apply_gradients_fn\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1340, in apply_grad_to_update_var\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tensorflow/core/function/polymorphism/function_type.py\", line 356, in placeholder_arguments\n\ttf2xla conversion failed while converting __inference__update_step_xla_279200[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.\n\t [[Adam/StatefulPartitionedCall_4]] [Op:__inference_train_function_280210]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[26], line 8\u001b[0m\n\u001b[1;32m      2\u001b[0m early_stopping \u001b[38;5;241m=\u001b[39m keras\u001b[38;5;241m.\u001b[39mcallbacks\u001b[38;5;241m.\u001b[39mEarlyStopping(\n\u001b[1;32m      3\u001b[0m     monitor\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mval_loss\u001b[39m\u001b[38;5;124m\"\u001b[39m, patience\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m5\u001b[39m, restore_best_weights\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m\n\u001b[1;32m      4\u001b[0m )\n\u001b[1;32m      6\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mStart training the model...\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m----> 8\u001b[0m \u001b[43mmodel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m      9\u001b[0m \u001b[43m    \u001b[49m\u001b[43mtraining_dataset\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     10\u001b[0m \u001b[43m    \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mnum_epochs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     11\u001b[0m \u001b[43m    \u001b[49m\u001b[43mvalidation_data\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mvalidation_dataset\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     12\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;66;43;03m# callbacks=[early_stopping],\u001b[39;49;00m\n\u001b[1;32m     13\u001b[0m \u001b[43m)\u001b[49m\n\u001b[1;32m     14\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mModel training finished.\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[0;32m~/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     67\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m     68\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[38;5;66;03m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m---> 70\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m     71\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     72\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tensorflow/python/eager/execute.py:53\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     52\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 53\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     54\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     56\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node DebugNumericSummaryV2 defined at (most recent call last):\n<stack traces unavailable>\nDetected at node DebugNumericSummaryV2 defined at (most recent call last):\n<stack traces unavailable>\nDetected unsupported operations when trying to compile graph __inference__update_step_xla_279200[] on XLA_GPU_JIT: DebugNumericSummaryV2 (No registered 'DebugNumericSummaryV2' OpKernel for XLA_GPU_JIT devices compatible with node {{node DebugNumericSummaryV2}}){{node DebugNumericSummaryV2}}\nThe op is created at: \nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py\", line 87, in _run_code\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/events.py\", line 80, in _run\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\nFile \"tmp/ipykernel_78405/2435027649.py\", line 8, in <module>\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1807, in fit\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1401, in train_function\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1384, in step_function\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1373, in run_step\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1154, in train_step\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 544, in minimize\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1223, in apply_gradients\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 652, in apply_gradients\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1253, in _internal_apply_gradients\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1345, in _distributed_apply_gradients_fn\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1340, in apply_grad_to_update_var\nFile \"home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tensorflow/core/function/polymorphism/function_type.py\", line 356, in placeholder_arguments\n\ttf2xla conversion failed while converting __inference__update_step_xla_279200[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.\n\t [[Adam/StatefulPartitionedCall_4]] [Op:__inference_train_function_280210]"
     ]
    }
   ],
   "source": [
    "# Create an early stopping callback.\n",
    "early_stopping = keras.callbacks.EarlyStopping(\n",
    "    monitor=\"val_loss\", patience=5, restore_best_weights=True\n",
    ")\n",
    "\n",
    "print(\"Start training the model...\")\n",
    "\n",
    "model.fit(\n",
    "    training_dataset,\n",
    "    epochs=num_epochs,\n",
    "    validation_data=validation_dataset,\n",
    "    # callbacks=[early_stopping],\n",
    ")\n",
    "print(\"Model training finished.\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Evaluating model performance...\")\n",
    "_, accuracy = model.evaluate(testing_dataset)\n",
    "print(f\"Test accuracy: {round(accuracy * 100, 2)}%\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "PvofpNi01Fh1"
   },
   "source": [
    "You should achieve more than 95% accuracy on the test set.\n",
    "\n",
    "To increase the learning capacity of the model, you can try increasing the\n",
    "`encoding_size` value, or stacking multiple GRN layers on top of the VSN layer.\n",
    "This may require to also increase the `dropout_rate` value to avoid overfitting."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "3rGQlNoI1Fh1"
   },
   "source": [
    "**Example available on HuggingFace**\n",
    "\n",
    "| Trained Model | Demo |\n",
    "| :--: | :--: |\n",
    "| [![Generic badge](https://img.shields.io/badge/%F0%9F%A4%97%20Model-Classification%20With%20GRN%20%26%20VSN-red)](https://huggingface.co/keras-io/structured-data-classification-grn-vsn) | [![Generic badge](https://img.shields.io/badge/%F0%9F%A4%97%20Space-Classification%20With%20GRN%20%26%20VSN-red)](https://huggingface.co/spaces/keras-io/structured-data-classification-grn-vsn) |"
   ]
  }
 ],
 "metadata": {
  "accelerator": "GPU",
  "colab": {
   "name": "classification_with_grn_and_vsn",
   "provenance": [],
   "toc_visible": true
  },
  "kernelspec": {
   "display_name": "astro_quality",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.18"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
